Updated JobSet and Kueue configuration

diff --git a/ai-infrastructure/tpu-training-on-gke/environment/cloudbuild.provision.yaml b/ai-infrastructure/tpu-training-on-gke/environment/cloudbuild.provision.yaml
--- a/ai-infrastructure/tpu-training-on-gke/environment/cloudbuild.provision.yaml
+++ b/ai-infrastructure/tpu-training-on-gke/environment/cloudbuild.provision.yaml
@@ -14,7 +14,7 @@
 
 steps:
   - id: log parameters 
-    name: gcr.io/cloud-builders/gcloud
+    name: gcr.io/cloud-builders/gke-deploy
     entrypoint: /bin/bash 
     args:
       - -c
@@ -47,72 +47,76 @@ steps:
 
   - id: tf output
     name: hashicorp/terraform
-    dir: 1-base-infrastructure  
     entrypoint: sh
+    dir: 1-base-infrastructure  
     args:
     - -c
     - |
       touch params.env
       echo "CLUSTER_NAME=$(terraform output cluster_name)" >> params.env 
       echo "CLUSTER_REGION=$(terraform output cluster_region)" >> params.env
-      cat params.env 
-
+      echo "KSA_NAME=$(terraform output wid_ksa_name)" >> params.env
+      echo "KSA_NAMESPACE=$(terraform output wid_ksa_namespace)" >> params.env
+      echo "GSA_EMAIL=$(terraform output wid_gsa_email)" >> params.env
 
   - id: 'Deploy JobSet'
-    name: gcr.io/cloud-builders/gcloud
-#    name: gcr.io/google.com/cloudsdktool/cloud-sdk 
-    dir: 1-base-infrastructure 
+    name: gcr.io/cloud-builders/gke-deploy
     entrypoint: /bin/bash
+    dir: 1-base-infrastructure  
     args:
       - -c
       - |
         set -o  allexport; source params.env; set +o allexport
         echo $$CLUSTER_NAME
         echo $$CLUSTER_REGION
-#        CLUSTER_NAME=
-#        gcloud container clusters get-credentials $_CLUSTER_NAME --region $_REGION
-#        kubectl apply --server-side -f "https://github.com/kubernetes-sigs/jobset/releases/download/$_JOBSET_API_VERSION/manifests.yaml" 
+        gcloud container clusters get-credentials $$CLUSTER_NAME --region $$CLUSTER_REGION
+        kubectl apply --server-side -f "https://github.com/kubernetes-sigs/jobset/releases/download/$_JOBSET_API_VERSION/manifests.yaml" 
 #
-#  - id: 'Deploy Kueue'
-#    name: gcr.io/google.com/cloudsdktool/cloud-sdk 
-#    entrypoint: /bin/bash
-#    args:
-#      - -c
-#      - |
-#        kubectl apply -f "https://github.com/kubernetes-sigs/kueue/releases/download/$_KUEUE_API_VERSION/manifests.yaml"
-#
-#  - id: 'Config Kueue'
-#    name: gcr.io/google.com/cloudsdktool/cloud-sdk 
-#    entrypoint: /bin/bash
-#    args:
-#      - -c
-#      - |
-#        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
-#        mv kustomize /usr/local/bin
-#        cd kueue
-#        kustomize edit set namespace $_NAMESPACE
-#        kustomize edit remove configmap tpu-config
-#        kustomize edit add configmap tpu-config --from-literal=NAME=$_TPU_TYPE --from-literal=NUM_OF_CHIPS=$_NUM_OF_CHIPS
-#        
-#        max_attempts=5
-#        attempt_num=1
-#        success=false
-#
-#        while [ $success = false ] && [ $attempt_num -le $max_attempts ]; do
-#          echo Sleep for a few seconds to avoid timeouts from Kueue
-#          sleep 10
-#          echo Attempting deployment of Kueue CRDs
-#          kubectl apply -k .
-#          if [ $? -eq 0 ]; then
-#            success=true
-#            echo Deployment of CRDs successful
-#          else
-#            echo "Deployment of CRDs faile"
-#            attempt_num=$(( attempt_num + 1 ))
-#          fi
-#        done
-#
-#
-#
-#
-# 
+  - id: 'Deploy Kueue'
+    name: gcr.io/cloud-builders/gke-deploy
+    entrypoint: /bin/bash
+    args:
+      - -c
+      - |
+        kubectl apply --server-side -f "https://github.com/kubernetes-sigs/kueue/releases/download/$_KUEUE_API_VERSION/manifests.yaml"
+
+  - id: 'Config Kueue'
+    name: gcr.io/cloud-builders/gke-deploy
+    entrypoint: /bin/bash
+    dir: 2-kubernetes-config 
+    args:
+      - -c
+      - |
+        set -o  allexport; source ../1-base-infrastructure/params.env; set +o allexport
+        cp ../1-base-infrastructure/templates/cluster_queue.yaml . 
+        kustomize edit set namespace $$KSA_NAMESPACE 
+        kustomize edit remove configmap tpu-config
+        kustomize edit add configmap wid-config --from-literal=ksa_name=$$KSA_NAME --from-literal=gsa_email=$$GSA_EMAIL --from-literal=cluster_queue=$_CLUSTER_QUEUE_NAME
+
+        max_attempts=5
+        attempt_num=1
+        success=false
+
+        while [ $success = false ] && [ $attempt_num -le $max_attempts ]; do
+          echo Sleep for a few seconds to avoid timeouts from Kueue
+          sleep 10
+          echo Attempting deployment of Kueue CRDs
+          kubectl apply -k .
+          if [ $? -eq 0 ]; then
+            success=true
+            echo Deployment of CRDs successful
+          else
+            echo "Deployment of CRDs failed"
+            attempt_num=$(( attempt_num + 1 ))
+          fi
+        done
+
+
+
+
+ 
+
+substitutions:
+  _JOBSET_API_VERSION: v0.3.0
+  _KUEUE_API_VERSION: v0.5.1
+  _CLUSTER_QUEUE_NAME: cluster-queue-1
